export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const UPDATE_ITEM_PROPERTIES = 'UPDATE_ITEM_PROPERTIES';